### ISSUE TITLE
Issue Memory Error

### ISSUE THREAD

**Issue by atnikos** [zonetrooper32/VDCNN#6]
I am getting a Memory Error when trying to run for yahoo answers dataset!I ll try to merge in dataset api in order to cache batches and not the whole dataset into memory.If i get through this maybe I ll fork from yours and contribute to repo!(The bug isn't sprecified exactly because what I get is Memory Error and not something more indicative)

**Comment by cjiang2** [comment]
Hi @nathan74 
Yeah since most of those NLP datasets are having some serious sizes, MemoryError is definitely an issue. Also I only have one cloud machine, and I can only do so few tests per day. :(
Let me know if you need the Collaborators access for cotributrion. It would be really nice to have some help. :)
